stages:
  - setup

variables:
  REPO_URL: "ssh://git@gitlab.webexpertsnepal.com:2020/sabin/vite-test.git"  # Default repository URL 
  PROJECT_NAME: vite_app # Use the GitLab project name as the folder name 
  GIT_HUB_REPO: "webexpertsnepal13/vite-test.git"
 

setup:
  stage: setup
  script:
    - bash /home/gitlab-runner/viteDeploy.sh $PROJECT_NAME $REPO_URL $GIT_HUB_REPO   # Run the script with project name and repo URL
  only:
    - main  # Specify which branch to trigger the pipeline on